@startuml
left to right direction

actor User

User --> (List orders)
User --> (Search order)
User --> (View order details)
User --> (Create order)
User --> (Delete order)

(Search order) --> (View order details) : <<include>>
(Create order) --> (List orders) : <<include>>
(Delete order) --> (List orders) : <<include>>

@enduml

User --> (Edit order)
(Edit order) --> (View order details) : <<include>>