@startuml
left to right direction

actor User

rectangle "Order Management System" {

  (List orders)
  (Search order)
  (View order details)
  (Create order)
  (Edit order)
  (Delete order)

  (Search order) --> (View order details) : <<include>>
  (Create order) --> (List orders) : <<include>>
  (Edit order) --> (View order details) : <<include>>
  (Delete order) --> (List orders) : <<include>>
}

User --> (List orders)
User --> (Search order)
User --> (View order details)
User --> (Create order)
User --> (Edit order)
User --> (Delete order)

@enduml
